defaults: &defaults
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: localhost

development:
  <<: *defaults
  database: siemens_development
  username: 
  password: 

test:
  <<: *defaults
  database: siemens_test
  username: 
  password: 

production:
  <<: *defaults
  database: siemenscollection
  username: 
  password: 

staging:
  <<: *defaults
  database: siemens_stage
  username: 
